Ft homepage
Elijahscriptdev/bootstrap_project pull request #2
Opened 2019-10-02 22:50 UTC by Elijahscriptdev

Newsweek: user interface

2019-10-03 04:59 UTC, maelfosso requested changes
Hello,

Thanks for the improvement.
Please the next time, don't create a new PR. Use the first one.

- [ ] Take a look on this image. To fix it, please, follow the suggestions left below.
![Screenshot from 2019-10-03 05-46-44](https://user-images.githubusercontent.com/8848104/66100256-1ddd0f00-e5a2-11e9-9439-3cf95d9825fd.png)

Kindly make that change and submit a new code review request.
Thanks.

2019-10-03 04:59 UTC, maelfosso commented on styles.css
> +  overflow-x: hidden;
remove it please

2019-10-03 04:59 UTC, maelfosso commented on index.html
> +          <ul class="d-flex  bd-highlight justify-content-between">
```css
{
   list-style: none;
}
```

2019-10-03 04:59 UTC, maelfosso commented on index.html
> +        <div class="row justify-content-center align-items-end logo-area ">
```css
{
   margin: 0;
}
```

2019-10-03 04:59 UTC, maelfosso commented on index.html
> +        <nav class="row navbar-light navbar bg-light pb-0 d-none d-md-block">
```css
{
   margin: 0;
}
```

2019-10-03 09:19 UTC, bolah2009 requested changes
## Awesome Job @Elijahscriptdev   :clap: 

#### The [clone](https://rawcdn.githack.com/Elijahscriptdev/bootstrap_project/b0c295a58c74c31f69dbc2837899ebada4bb30bc/index.html) looks nice..  Let's make it even better! :smile:

A few required changes :relaxed: 
- [REQUIRED] Let's use more of bootstrap as pointed out in the comments below (and in all other occurrences wherever possible) as **Using Bootstrap** is the main objective of this project.

  > Remember to use Bootstrap CSS classes wherever it is possible - this is the main point of this project.
 - [REQUIRED] Let's make sure the clone is as responsive as the source page.

   > As you can use a ready set of CSS classes, be more precise and make sure that your page looks exactly the same as the source page.
   > Remember to double-check if your page layout does not break on smaller screens.
- Fix [HTML validation warnings](https://validator.w3.org/nu/?doc=https%3A%2F%2Frawcdn.githack.com%2FElijahscriptdev%2Fbootstrap_project%2Fb0c295a58c74c31f69dbc2837899ebada4bb30bc%2Findex.html)
   > Validate your HTML markup with https://validator.w3.org/#validate_by_upload.
- Let's make this Pull Request look more professional. 
  - [NEXT PROJECT]: Use meaningful commits messages. [Learn more here](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)
  - [REQUIRED] Use meaningful names for  Pull Requests.
  - [REQUIRED] Add a short summary of changes in Pull Request description.

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-10-03 09:19 UTC, bolah2009 commented on index.html
> +        <nav class="row navbar-light navbar bg-light pb-0 d-none d-md-block">
Can we still hide this nav element for medium screens? :thinking:
Using `d-lg-block` instead of `d-md-block`.

Also, try and make this nav fit the window, see how it is currently rendered below:

| Current | Source Page |
| :-----: | :-----: |
| ![newweeknav](https://user-images.githubusercontent.com/36057474/66111815-88ea0e00-e5c1-11e9-8331-02e3002e78bf.png)  | ![newsweek nav source](https://user-images.githubusercontent.com/36057474/66111825-90111c00-e5c1-11e9-8922-a7e974061b70.png)  |

2019-10-03 09:19 UTC, bolah2009 commented on index.html
> +            <div class="col-sm featured-col">
This and other siblings should [use responsive grid class](https://getbootstrap.com/docs/4.1/layout/grid/). 
- For small screens, it should take 100% of the parent width
- For medium screens, it should take half of the width. The last section (`.opinion-col`) should take 100% of the parent width.

| Current | Source Page |
| :-----: | :-----: |
| ![top story clone](https://user-images.githubusercontent.com/36057474/66112835-7cff4b80-e5c3-11e9-8a6f-e2fc0dbc9105.png) | ![top story source](https://user-images.githubusercontent.com/36057474/66112862-8983a400-e5c3-11e9-89a8-e1b56fd5daa0.png)  |

2019-10-03 09:19 UTC, bolah2009 commented on styles.css
> +    display: block;
Consider using a `Bootstrap` class name for this selector element and in all other occurrences instead.

Bootstrap class names can be used instead. See [Display](https://getbootstrap.com/docs/4.1/utilities/display/) in bootstrap documentation.

> Remember to use Bootstrap CSS classes wherever it is possible - this is the main point of this project.

#### Please, lets do this for all other occurrences. :blush:

2019-10-03 09:19 UTC, bolah2009 commented on styles.css
> +    float: left !important;
Always look for a way to use [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) before even considering `!important`. 

Learn more [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#The_!important_exception)

> Make sure you DON’T make [common mistakes](https://speckyboy.com/good-bad-css-practices/) in your CSS styles.

> **Recommendation:** You should only use the !important rule when overriding styles in a user style sheet, overriding 3rd party code and inline styles as well as utility classes.

2019-10-03 09:19 UTC, bolah2009 commented on styles.css
> +  position: absolute;
Consider using a `Bootstrap` class name for this selector element and in all other occurrences instead.

Bootstrap class names can be used instead. See [Position](https://getbootstrap.com/docs/4.1/utilities/position/) in bootstrap documentation.

> Remember to use Bootstrap CSS classes wherever it is possible - this is the main point of this project.

#### Please, lets do this for all other occurrences. :blush:

2019-10-03 09:19 UTC, bolah2009 commented on styles.css
> +  margin: auto;
Consider using a `Bootstrap` class name for this selector element and in all other occurrences instead.

`mx-auto` Bootstrap class name can be used instead. See [horizontal centering](https://getbootstrap.com/docs/4.1/utilities/spacing/#horizontal-centering) in bootstrap documentation.

> Remember to use Bootstrap CSS classes wherever it is possible - this is the main point of this project.

#### Please, lets do this for all other occurrences. :blush:

2019-10-03 21:40 UTC, Redvanisation requested changes
### Hello @Elijahscriptdev   🌟

**Great job so far, however before I can approve your project you have to implement all the changes requested in the previous reviews**

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-10-05 01:27 UTC, bolah2009 requested changes
Hi @Elijahscriptdev 

The navbar is not as responsive as it should be yet. Have you tried testing it with the dev tools responsive view? See the illustration below. Also, chat me up on slack if you having issues fixing this bug.

![bootstrap current gif](https://user-images.githubusercontent.com/36057474/66247666-67029f80-e717-11e9-8c74-d15dcbc86f87.gif)

2019-10-05 04:09 UTC, bolah2009 requested changes
Let's check if this suggestions fix the nav bar.

2019-10-05 04:09 UTC, bolah2009 commented on index.html
> +          <ul class="d-flex  bd-highlight justify-content-between">
Let's change `justify-content-between` to `justify-content-center`

2019-10-05 04:09 UTC, bolah2009 commented on styles.css
> +  padding: 0 1rem;
Let's set this padding to 0.
```suggestion
  padding: 0;
```

Also, let's add style for the parent element, `li`

```css
.nav-item {
    flex-grow: 1;
    text-align: center;
}
```

And for the list `ul`

```css
ul.bd-highlight {
    width: 100%;
}
```

2019-10-05 10:23 UTC, samgaco approved these changes
Hi @Elijahscriptdev :high_brightness: 

The project is approved :heavy_check_mark:  you can merge to the master branch and submit the project completion form.



-----------------------------


**[OPTIONAL]**

- I would suggest fixing these sections in the middle-sized screen which should be taking the whole width of the site:


> ![opinion](https://user-images.githubusercontent.com/34820784/66253555-bd4cfe00-e76a-11e9-8a89-990c941e7eb0.png)


---------------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-10-05 10:23 UTC, samgaco commented on index.html
> +          <ul class="d-flex  bd-highlight justify-content-center">
:+1:

2019-10-05 13:45 UTC, merged